config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'reservations/index'
  get 'reservations/new'
  get 'reservations/show'
  post 'reservations/confirm'
  post 'reservations/back'
  post 'reservations/complete'

  get 'rooms/index'
  get 'rooms/new'

  get 'users/profile'
  get 'users/edit_profile', to: 'users#edit_profile'
  get 'users/update'
  get 'users/login'
  get 'users/account'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get '/users/sign_up' => 'devise/registrations#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'rooms#top'

  resources :rooms do
    collection do
      get 'search'
    end
  end

  resources :users, only: %i[edit update] do
    member do
      get 'edit_profile'
    end
  end

  resources :reservations

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
       # Include default devise modules. Others available are:
       # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
       devise :database_authenticatable, :registerable,
              :recoverable, :rememberable, :validatable
     
       has_many :rooms
       has_many :reservations
     
       has_one_attached :profile_image
     
       attr_accessor :current_password
 end

app/controllers/user_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    def update
      @user = current_user
      @user.profile_image.attach(params[:profile_image])
      @user.name = params[:name]
      @user.introduction = params[:introduction]
  
      if @user.update(profile_image: params[:profile_image], name: params[:name], introduction: params[:introduction])
        flash[:notice] = '変更が完了しました'
        redirect_to :rooms
      else
        flash[:alert] = '変更に失敗しました'
        render 'users/profile'
      end
    end
  
    def account
      @user = User.find_by(id: params[:id])
    end
  
    def profile
      @user = User.find_by(id: params[:id])
    end
  
    def edit_profile
      @user = User.find_by(id: params[:id])
    end
  end

app/controllers/users/confirmations_controller.rb
module Users
    class ConfirmationsController < Devise::ConfirmationsController
      # GET /resource/confirmation/new
      # def new
      #   super
      # end
  
      # POST /resource/confirmation
      # def create
      #   super
      # end
  
      # GET /resource/confirmation?confirmation_token=abcdef
      # def show
      #   super
      # end
  
      # protected
  
      # The path used after resending confirmation instructions.
      # def after_resending_confirmation_instructions_path_for(resource_name)
      #   super(resource_name)
      # end
  
      # The path used after confirmation.
      # def after_confirmation_path_for(resource_name, resource)
      #   super(resource_name, resource)
      # end
    end
  end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
    class OmniauthCallbacksController < Devise::OmniauthCallbacksController
      # You should configure your model like this:
      # devise :omniauthable, omniauth_providers: [:twitter]
  
      # You should also create an action method in this controller like this:
      # def twitter
      # end
  
      # More info at:
      # https://github.com/heartcombo/devise#omniauth
  
      # GET|POST /resource/auth/twitter
      # def passthru
      #   super
      # end
  
      # GET|POST /users/auth/twitter/callback
      # def failure
      #   super
      # end
  
      # protected
  
      # The path used when OmniAuth fails
      # def after_omniauth_failure_path_for(scope)
      #   super(scope)
      # end
    end
  end

app/controllers/users/passwords_controller.rb
module Users
    class PasswordsController < Devise::PasswordsController
      # GET /resource/password/new
      # def new
      #   super
      # end
  
      # POST /resource/password
      # def create
      #   super
      # end
  
      # GET /resource/password/edit?reset_password_token=abcdef
      # def edit
      #   super
      # end
  
      # PUT /resource/password
      # def update
      #   super
      # end
  
      # protected
  
      # def after_resetting_password_path_for(resource)
      #   super(resource)
      # end
  
      # The path used after sending reset password instructions
      # def after_sending_reset_password_instructions_path_for(resource_name)
      #   super(resource_name)
      # end
    end
  end

app/controllers/users/registrations_controller.rb
module Users
    class RegistrationsController < Devise::RegistrationsController
      before_action :configure_sign_up_params, only: [:create]
      # before_action :configure_account_update_params, only: [:update]
  
      # GET /resource/sign_up
      # def new
      #   super
      # end
  
      # POST /resource
      # def create
      #   super
      # end
  
      # GET /resource/edit
      # def edit
      #   super
      # end
  
      # PUT /resource
      # def update
      #   super
      # end
  
      # DELETE /resource
      # def destroy
      #   super
      # end
  
      # GET /resource/cancel
      # Forces the session data which is usually expired after sign
      # in to be expired now. This is useful if the user wants to
      # cancel oauth signing in/up in the middle of the process,
      # removing all OAuth session data.
      # def cancel
      #   super
      # end
  
      protected
  
      def update_resource(resource, params)
        resource.update_without_password(params)
      end
  
      # If you have extra params to permit, append them to the sanitizer.
      def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      end
  
      # If you have extra params to permit, append them to the sanitizer.
      # def configure_account_update_params
      #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
      # end
  
      # The path used after sign up.
      # def after_sign_up_path_for(resource)
      #   super(resource)
      # end
  
      # The path used after sign up for inactive accounts.
      # def after_inactive_sign_up_path_for(resource)
      #   super(resource)
      # end
    end
  end

app/views/users/accountのコピー.html.erb
<%= render "shared/switching" %>

<h3>アカウント</h3>

  <table>
    <tr>
      <th>メールアドレス</th>
      <th>パスワード</th>
    </tr>

    <tr>
      <td><%= current_user.email %></td>
      <td>＊＊＊＊＊＊＊</td>
    </tr>
  </table>

  <div>
    <%= link_to "編集", "/users/edit" %>
  </div>

app/views/users/edit_profileのコピー.html.erb
<%= render "shared/switching" %>

<h3>プロフィール編集</h3>

<%= form_with model: @user, url: users_update_path, method: :patch do |f| %>
  <div class="form-group">
    <%= f.label :profile_image, "プロフィール画像" %>
    <%= f.file_field :profile_image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name, "名前" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :introduction, "自己紹介" %>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "変更を保存", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/newのコピー.html.erb
<h3>ユーザー新規登録</h3>

<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/users/profileのコピー.html.erb
<%= render "shared/switching" %>

<h3>プロフィール</h3>

  <table>
    <tr>
      <th>画像</th>
      <th>名前</th>
      <th>自己紹介</th>
    </tr>

    <tr>
      <% if current_user.profile_image.present? %>
        <td><%= image_tag current_user.profile_image %></td>
      <% else %>
        <td><%= image_tag "icon_avater.png" %></td>
      <% end %>
      <td><%= current_user.name %></td>
      <td><%= current_user.introduction %></td>

    </tr>
  </table>

  <div>
    <%= link_to "編集", "/users/edit_profile" %>
  </div>