config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'reservations/index'
  get 'reservations/new'
  get 'reservations/show'
  post 'reservations/confirm'
  post 'reservations/back'
  post 'reservations/complete'

  get 'rooms/index'
  get 'rooms/new'

  get 'users/profile'
  get 'users/edit_profile', to: 'users#edit_profile'
  get 'users/update'
  get 'users/login'
  get 'users/account'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get '/users/sign_up' => 'devise/registrations#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'rooms#top'

  resources :rooms do
    collection do
      get 'search'
    end
  end

  resources :users, only: %i[edit update] do
    member do
      get 'edit_profile'
    end
  end

  resources :reservations

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_form.html.erb
<%= form_with model: Reservation.new, local: true, url: reservations_confirm_path do |f| %>
    <div class="card">
      <div class="card-header">
        <h5>施設予約入力</h5>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :price, value: @room.price %>
      </div>
      <div class="card-body">
        <div class="form-row">
          <div class="col">
            <%= f.label :check_in, "チェックイン" %>
            <%= f.date_field :check_in, placeholder: "チェックイン", class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :check_out, "チェックアウト" %>
            <%= f.date_field :check_out, placeholder: "チェックアウト", class: "form-control" %>
          </div>
          <div class="col">
            <%= f.label :people, "宿泊人数" %>
            <%= f.number_field :people, placeholder: "人", class: "form-control" %>
          </div>
        </div>
      <br/>
        <%= f.submit "予約する", id: "btn_book", class: "btn btn-danger btn-block" %>
      </div>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<div class = header-list>
  <p class="header-logo"><%= link_to "Potepan_reseve","/" %></p>
  <% if user_signed_in? %>
    <div class="dropdown">
      <div class="header-icon">
        <% if current_user.profile_image.present? %>
          <td><%= image_tag current_user.profile_image %></td>
        <% else %>
          <td><%= image_tag "icon_avater.png" %></td>
        <% end %>
      </div>
      <div class = "user_name">
        <div class="btn-group dropleft">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item"><%= link_to "施設の新規登録", new_room_path %></a>
            <a class="dropdown-item"><%= link_to "予約済み一覧", reservations_path %></a>
            <a class="dropdown-item"><%= link_to "登録済み一覧", rooms_path %></a>
            <a class="dropdown-item"><%= link_to "アカウント設定", '/users/account' %></a>
            <a class="dropdown-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></a>
          </div>
        </div>
      </div>
    </div>

  <% else %>
    <div>
      <%= link_to "ログイン", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
    </div>
  <% end %>
</div>